config/routes.rb
Rails.application.routes.draw do
  get 'about/index'
  get 'about' => "about#index"

  get 'authors/new'

  get 'authors/create'

  get 'authors/update'

  get 'authors/edit'

  get 'authors/destroy'

  get 'authors/index'

  get 'authors/show'

  get 'publishers/new'

  get 'publishers/create'

  get 'publishers/update'

  get 'publishers/edit'

  get 'publishers/destroy'

  get 'publishers/index'

  get 'publishers/show'

  get 'categories/new'

  get 'categories/create'

  get 'categories/update'

  get 'categories/edit'

  get 'categories/destroy'

  get 'categories/index'

  get 'categories/show'

  get 'books/new'

  get 'books/create'

  get 'books/update'

  get 'books/edit'

  get 'books/destroy'

  get 'books/index'

  get 'books/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'books#index'

  resources :publishers
  resources :books
  resources :authors
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
	has_many :books
	validates :first_name, presence: true
	validates :last_name, presence: true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :category
	belongs_to :author
	belongs_to :publisher



end

app/models/category.rb
class Category < ApplicationRecord
	has_many :books

	validates :name, presence: true, length: {minimum:3}
end

app/models/publisher.rb
class Publisher < ApplicationRecord
	has_many :books
	validates :name, presence: true, length: {minimum:3}

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  	@page_title = 'This is about us page';
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def new
    @page_title = "Add new Author"
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if
      @author.save
      flash[:notice] = "Author Created"
        redirect_to authors_path
    else
      render 'new'
    end
  end

    


  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end

  private
  def author_params
    params.require(:author).permit(:first_name, :last_name)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @page_title = 'Add a Book'
    @book = Book.new
    @category = Category.new
    @author = Author.new
    @publisher = Publisher.new
  end

  def create
    @book = Book.new(book_params)
    if 
      @book.save
      flash[:notice] = "Book Created"
        redirect_to books_path
    else
      render 'new'
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    flash[:notice] = 'book added'
    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
  end

  def destroy 
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "book deleted"
    redirect_to books_path
  end


  def index
    @book = Book.all
    @category = Category.all

  end

  def show
    @book = Book.find(params[:id])
    @category = Category.all
  end

  private
  def book_params
    params.require(:book).permit(:title, :category_id, :author_id, :publisher_id, :isbn, :excerpt, :pages, :price, :buy, :format, :year, :coverpath, :format)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
       @page_title = "Add new Category"
        @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if 
      @category.save
      flash[:notice] = "Category Created"
        redirect_to categories_path
    else
      render 'new'
    end
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def new
       @page_title = "Add new Publisher"
    @publisher = Publisher.new
  end

  def create
    @publisher = Publisher.new(publisher_params)
    if
       @publisher.save 
       flash[:notice] = "Publisher Created"
       redirect_to publishers_path
    else
      render 'new'
    end
  end


  

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end

  private
  def publisher_params
    params.require(:publisher).permit(:name)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/about/index.html.erb
<h1>About Book Store</h1>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.</p>

<p>The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>

app/views/authors/create.html.erb
<h1>Authors#create</h1>
<p>Find me in app/views/authors/create.html.erb</p>

app/views/authors/destroy.html.erb
<h1>Authors#destroy</h1>
<p>Find me in app/views/authors/destroy.html.erb</p>

app/views/authors/edit.html.erb
<h1>Authors#edit</h1>
<p>Find me in app/views/authors/edit.html.erb</p>

app/views/authors/index.html.erb
<h1>Authors#index</h1>
<p>Find me in app/views/authors/index.html.erb</p>

app/views/authors/new.html.erb
<h1>Add a New Author</h1>

<%= form_for @author do |f| %>

<% if @author.errors.any? %>
	<% @author.errors.full_messages.each do |msg| %>
	<div class="alert alert-danger"><%= msg %></div>
	<% end %>
<% end%>

<div class="form-group">
<%= f.label :first_name %><br/>
<%= f.text_field :first_name, class:'form-control' %><br/>
</div>

<div class="form-group">
<%= f.label :last_name %><br/>
<%= f.text_field :last_name, class:'form-control' %><br/>
</div>


<%= f.submit "Submit", class:'btn btn-primary' %>
<%= link_to "Cancel", authors_path, class:'btn btn-default' %>

<% end %>

app/views/authors/show.html.erb
<h1>Authors#show</h1>
<p>Find me in app/views/authors/show.html.erb</p>

app/views/authors/update.html.erb
<h1>Authors#update</h1>
<p>Find me in app/views/authors/update.html.erb</p>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<h1>Edit a Book</h1>
<%= form_for @book do |f| %>

<% if @book.errors.any? %>
	<% @book.errors.full_messages.each do |msg| %>
	<div class="alert alert-danger"><%= msg %></div>
	<% end %>
<% end%>

<div class="form-group">
<%= f.label :title %><br/>
<%= f.text_field :title, class:'form-control' %><br/>
</div>

<div class="form-group">
<%= f.label :isbn %><br/>
<%= f.text_field :isbn, class:'form-control' %><br/>
</div>

<div class="form-group">
<%= f.label :category %><br/>
<%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'}, class:'form-control' %><br/><br/>
</div>

<div class="form-group">
<%= f.label :author %><br/>
<%= f.select :author_id, Author.all.collect {|x| [x.first_name + ' ' + x.last_name, x.id]}, {:include_blank => 'Select One'}, class:'form-control' %><br/><br/>
</div>

<div class="form-group">
<%= f.label :publisher %><br/>
<%= f.select :publisher_id, Publisher.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'}, class:'form-control' %><br/><br/>
</div>

<div class="form-group">
<%= f.label :excerpt %><br/>
<%= f.text_area :excerpt, class:'form-control' %><br/>
</div>

<div class="form-group">
<%= f.label :pages %><br/>
<%= f.text_field :pages, class:'form-control' %><br/>
</div>

<div class="form-group">
<%= f.label :year %><br/>
<%= f.text_field :year, class:'form-control' %><br/>
</div>

<div class="form-group">
<%= f.label :coverpath %><br/>
<%= f.text_field :coverpath, class:'form-control' %><br/>
</div>


<div class="form-group">
<%= f.label :price %><br/>
<%= f.text_field :price, class:'form-control' %><br/>
</div>

<div class="form-group">
<%= f.label :buy %><br/>
<%= f.text_field :buy, class:'form-control' %><br/>
</div>

<div class="form-group">
<%= f.label :format %><br/>
<%= f.text_field :format, class:'form-control' %><br/>
</div>


<%= f.submit "Submit", class:'btn btn-primary' %>
<%= link_to "Cancel", books_path, class:'btn btn-default' %>
<% end %>

app/views/books/index.html.erb
<div id="books-index">
	<% @book.each_slice(4) do |book| %>
		<div class="row">
			<% book.each do |book| %>
				<div class="col-md-3 col-md-3">
					<h3><%= book.title %></h3>
					<%= image_tag(book.coverpath) %>
					<%= link_to 'Read More', book_path(book), class:"btn btn-primary" %>
				</div>
			<% end %>
		</div>
	<% end %>	

	

</div>

app/views/books/new.html.erb
<h1>Add a New Book</h1>
<%= form_for @book do |f| %>

<% if @book.errors.any? %>
	<% @book.errors.full_messages.each do |msg| %>
	<div class="alert alert-danger"><%= msg %></div>
	<% end %>
<% end%>

<div class="form-group">
<%= f.label :title %><br/>
<%= f.text_field :title, class:'form-control' %><br/>
</div>

<div class="form-group">
<%= f.label :isbn %><br/>
<%= f.text_field :isbn, class:'form-control' %><br/>
</div>

<div class="form-group">
<%= f.label :category %><br/>
<%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'}, class:'form-control' %><br/><br/>
</div>

<div class="form-group">
<%= f.label :author %><br/>
<%= f.select :author_id, Author.all.collect {|x| [x.first_name + ' ' + x.last_name, x.id]}, {:include_blank => 'Select One'}, class:'form-control' %><br/><br/>
</div>

<div class="form-group">
<%= f.label :publisher %><br/>
<%= f.select :publisher_id, Publisher.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'}, class:'form-control' %><br/><br/>
</div>

<div class="form-group">
<%= f.label :excerpt %><br/>
<%= f.text_area :excerpt, class:'form-control' %><br/>
</div>

<div class="form-group">
<%= f.label :pages %><br/>
<%= f.text_field :pages, class:'form-control' %><br/>
</div>

<div class="form-group">
<%= f.label :year %><br/>
<%= f.text_field :year, class:'form-control' %><br/>
</div>

<div class="form-group">
<%= f.label :coverpath %><br/>
<%= f.text_field :coverpath, class:'form-control' %><br/>
</div>


<div class="form-group">
<%= f.label :price %><br/>
<%= f.text_field :price, class:'form-control' %><br/>
</div>

<div class="form-group">
<%= f.label :buy %><br/>
<%= f.text_field :buy, class:'form-control' %><br/>
</div>

<div class="form-group">
<%= f.label :format %><br/>
<%= f.text_field :format, class:'form-control' %><br/>
</div>


<%= f.submit "Submit", class:'btn btn-primary' %>
<%= link_to "Cancel", books_path, class:'btn btn-default' %>
<% end %>

app/views/books/show.html.erb
<div id="books-show">
<h2><%= @book.title %></h2>
<div class="books-show-left">
	<%= image_tag(@book.coverpath) %>
</div>
<div class="books-show-right">
<h3>What Can I give</h3>
<ul>
<li><strong>Category: </strong><%= @book.category.name %></li>
<li><strong>Author: </strong><%= @book.author.first_name + ' '+ @book.author.last_name %></li>
<li><strong>Publisher: </strong><%= @book.publisher.name %></li>
<li><strong>Year </strong><%= @book.year %></li>
<li><strong>ISBN: </strong><%= @book.isbn %></li>
<li><strong>Format: </strong><%= @book.format %></li>
<li><strong>Pages: </strong><%= @book.pages %></li>
</ul>
<%= link_to "Buy for $3.54", @book.buy, class:'btn btn-success', target:'_blank' %>
</div>
<div class="clearfix"></div>
<h4>Excerpt:</h4>
<p><%= @book.excerpt %></p>
</div>
<hr>
<h3>Admin Panel</h3>
<%= link_to 'Edit', edit_book_path(@book.id) %> | <%= link_to 'Delete', book_path(@book), method:  :delete, data:{confirm: 'Are you sure?'} %>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/categories/new.html.erb
<h1>Add a New Category</h1>
<%= form_for @category do |f| %>

<% if @category.errors.any? %>
	<% @category.errors.full_messages.each do |msg| %>
	<div class="alert alert-danger"><%= msg %></div>
	<% end %>
<% end%>

<div class="form-group">
<%= f.label :name %><br/>
<%= f.text_field :name, class:'form-control' %><br/>
</div>


<%= f.submit "Submit", class:'btn btn-primary' %>
<%= link_to "Cancel", categories_path, class:'btn btn-default' %>

<% end %>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title ? @page_title : "welcome to our store" %> | Bookstore</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Books Store</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= params[:controller] == 'books' ? 'active' : '' %>"><%= link_to 'Home', root_path %></li>
        <li class="<%= params[:controller] == 'about' ? 'active' : '' %>"><%= link_to 'About', about_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Add New <span class="caret"></span></a>
          	<ul class="dropdown-menu">
	            <li><%= link_to 'Books', new_book_path %></li>
	            <li><%= link_to 'Categories', new_category_path %></li>
	            <li><%= link_to 'Publishers', new_publisher_path %></li>
	            <li><%= link_to 'Authors', new_author_path %></li>
        	</ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Manage Option <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Books', new_book_path %></li>
              <li><%= link_to 'Categories', new_category_path %></li>
              <li><%= link_to 'Publishers', new_publisher_path %></li>
              <li><%= link_to 'Authors', new_author_path %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<header>
	<div class="container">
		<h1>The Book Store <small><%= @page_title ? @page_title : "Welcome to our store" %></small></h1>
	</div>
</header>
<section>
	<div class="container">
		<div class="row">
		 	<div class="col-md-8">
      <% if flash[:notice] %>
      <div class="alert alert-success"><%= flash[:notice] %></div>
      <% end %>
      <% if flash[:alert] %>
      <div class="alert alert-danger"><%= flash[:alert] %></div>
      <% end %>
    			<%= yield %>
    		</div>
    		<div class="col-md-4">
    		 	<%= render 'partials/sidebar' %>
    		</div>
    	</div>
    </div>
</section>
<footer>
	<div class="container">
		@copyright - 2016 - All rights are reserved by Bookstore.com
	</div>
</footer>
  </body>
</html>

app/views/partials/_sidebar.html.erb
<% if params[:controller] == 'about' %>
	<div class="well">
	<h3>Location info</h3>
		<ul>
			<li>Netcracker Online Services Pvt. Ltd.</li>
			<li>#275/5, 15th Main, Sadashivnagar</li>
			<li>Bangalore - 560 080</li>
			<li>Phone: 080 6531-6321</li>
			<li>Email: Info@knewcleus.com</li>
		</ul>
	</div>
<% end %>

<% if params[:controller] == 'books' && params[:action] == 'index' || params[:action] == 'show' %>
<div class="list-group">

<% @category.each do |category| %>
<%= link_to category.name, category_path(category.id), class:'list-group-item' %>
<% end %>
 

</div>
<% end %>

app/views/publishers/create.html.erb
<h1>Publishers#create</h1>
<p>Find me in app/views/publishers/create.html.erb</p>

app/views/publishers/destroy.html.erb
<h1>Publishers#destroy</h1>
<p>Find me in app/views/publishers/destroy.html.erb</p>

app/views/publishers/edit.html.erb
<h1>Publishers#edit</h1>
<p>Find me in app/views/publishers/edit.html.erb</p>

app/views/publishers/index.html.erb
<h1>Publishers#index</h1>
<p>Find me in app/views/publishers/index.html.erb</p>

app/views/publishers/new.html.erb
<h1>Add a New Publisher</h1>

<%= form_for @publisher do |f| %>

<% if @publisher.errors.any? %>
	<% @publisher.errors.full_messages.each do |msg| %>
	<div class="alert alert-danger"><%= msg %></div>
	<% end %>
<% end%>


<div class="form-group">
<%= f.label :name %><br/>
<%= f.text_field :name, class:'form-control' %><br/>
</div>


<%= f.submit "Submit", class:'btn btn-primary' %>
<%= link_to "Cancel", publishers_path, class:'btn btn-default' %>

<% end %>

app/views/publishers/show.html.erb
<h1>Publishers#show</h1>
<p>Find me in app/views/publishers/show.html.erb</p>

app/views/publishers/update.html.erb
<h1>Publishers#update</h1>
<p>Find me in app/views/publishers/update.html.erb</p>